version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/app

  webserver:
    image: nginx:stable-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}