version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile

  webserver:
    image: nginx:stable-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app
      - ./docker/nginx:/etc/nginx/conf.d